#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1'
bspc rule -a kitty desktop='^3'
bspc rule -a codium desktop='^4'
bspc rule -a nautilus desktop='^5'
bspc rule -a spotify desktop='^0'


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
killall flameshot picom nm-applet xsetroot xfce4-power-manager numlockx nitrogen parcellite
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/lib/xfce4/notifyd/xfce4-notifyd &
#/usr/bin/dunst &
# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/libexec/polkit-gnome-authentication-agent-1 &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Power Manager
xfce4-power-manager &
# Clipboard
parcellite &
# Wallpaper setter
nitrogen --restore &
# Screenshot app
flameshot &
#numlock on
numlockx &
# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh

